{
 "title": "EKS Platform Observability",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Rate by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(sre_demo_requests_total[1m]))",
     "legendFormat": "{{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "rate(sre_demo_request_latency_seconds_sum[1m])\r\n/\r\nrate(sre_demo_request_latency_seconds_count[1m])",
     "legendFormat": "{{pod}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"sre-demo-app\", container=\"sre-demo-app\"}",
     "legendFormat": "Pod {{pod}}"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_pod_status_ready{namespace=\"sre-demo-app\",condition=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"sre-demo-app\",container=\"sre-demo-app\"}[1m])) by (pod) * 100",
     "legendFormat": "Pod {{pod}}"
    }
   ]
  }
 ]
}