{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sre-demo-app
  labels:
    app.kubernetes.io/name: sre-demo-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sre-demo-app
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}