replicaCount: 2

image:
  repository: 205930609978.dkr.ecr.us-east-1.amazonaws.com/sre-demo-app
  tag: 1e648d3
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: sre-demo-app

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: eks.rehangatus.click
  tls:
    enabled: true
    secretName: sre-demo-app-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: eks.rehangatus.click

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /readyz-broken
    initialDelaySeconds: 5
    periodSeconds: 5

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

pdb:
  enabled: true
  minAvailable: 1

serviceMonitor:
  enabled: true
  path: /metrics
  interval: 15s

networkPolicy:
  enabled: true
